# Generated by Django 4.2 on 2023-10-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformeDna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('numero', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('respuesta', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=200)),
            ],
        ),
    ]
