"""
Django settings for cargosystem project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
from django.contrib import messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PACKAGE_ROOT = os.path.abspath(os.path.dirname(__file__))
RUTA_PROYECTO = os.path.dirname(os.path.realpath(__file__))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e-1*c(&*w!hbn1r9ok^5q)p1sut-snx*2r-u9u^9rtbk((-c48'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = False
ALLOWED_HOSTS = ["*"]
DAPHNE_PORT=8002
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
URL_DESCONSOLIDACION='http://www.importsys.com.uy/ws/wsOcean.exe'
# Application definition

INSTALLED_APPS = [
    # 'dal',
    # 'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'login',
    'mantenimientos',
    'seguimientos',
    'widget_tweaks',
    'auditlog',
    'notificaciones',
    'informedna',
    'impomarit',
    'expmarit',
    'impaerea',
    'expaerea',
    'impterrestre',
    'administracion_contabilidad',
    'consultas_administrativas',
    'expterrestre',
    'channels',
]

# Configura ASGI como entrada principal
ASGI_APPLICATION = "cargosystem.asgi.application"

# Configura Redis como layer para canales
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': { 'class': 'logging.StreamHandler' },
#     },
#     'root': {
#         'handlers': ['console'],
#         'level': 'DEBUG',
#     },
# }


CSRF_COOKIE_SECURE = False
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter',
             'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ]
    },
    'awesome_ckeditor': {
        'toolbar': 'Basic',
    },
}
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'administracion_contabilidad.middleware.VerificarArbitrajeMiddleware',
    'cargosystem.middleware.RolPorPestanaMiddleware',
    'cargosystem.middleware.RolRedirectMiddleware',
    'cargosystem.middleware.BloqueoModalMiddleware',
    'cargosystem.middleware.RolActivoMiddleware'
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'cargosystem.validators.CustomPasswordValidator',
    },
]


ROOT_URLCONF = 'cargosystem.urls'

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'cargosystem/media'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PACKAGE_ROOT, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'cargosystem.context_processors.rol_pestana'
            ],
            'libraries': {
                'my_templatetag': 'seguimientos.templatetags.filtros',

            }
        },
    },
]
WSGI_APPLICATION = 'cargosystem.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        #'NAME': 'cargosystem_prod',
        'NAME': 'cargosystem',
        # 'NAME': 'cargo',
        #'USER': 'sistemas',
        'USER': 'root',
        'PASSWORD': 'Rincon@1956',
        # 'PASSWORD': 'PassCargo2023',
        #'HOST': 'opensoft.uy',
        'HOST': 'localhost',
        'PORT': '3306',
        "OPTIONS": {
            'init_command': "SET default_storage_engine='INNODB'; SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'
TIME_ZONE = 'America/Montevideo'
USE_I18N = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRONJOBS = [
    ('*/2 * * * *', 'cargosystem.cron.liberar_bloqueos_expirados'),  # cada 2 minutos
]

STATICFILES_DIRS = (
    os.path.join(RUTA_PROYECTO, 'static'),
    os.path.join(RUTA_PROYECTO, 'media'),
    os.path.join(BASE_DIR, 'mantenimientos/static'),
    os.path.join(BASE_DIR, 'seguimientos/static'),
    os.path.join(BASE_DIR, 'administracion_contabilidad/static'),

)
RUTA_ARCHIVOS = str(RUTA_PROYECTO) + '/media/archivos_adjuntos/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
EMPRESA = 'Oceanlink Group'
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field


# EMAIL CONFIGURATION

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST = 's109.nty.uy'
# EMAIL_HOST_USER = 'opensoft@oceanlinkgroup.com'
EMAIL_HOST_USER = 'belen.albano@opensoft.com.uy'
EMAIL_HOST_PASSWORD = '6EPCuBByz8zS'
# EMAIL_HOST_PASSWORD = 'W}}WN-~bn=Bl'
EMAIL_PORT = 465
DEFAULT_FROM_EMAIL = 'opensoft@oceanlinkgroup.com'


EMPRESA_HAWB = 'OCEANLINK' + '<br />\n' + 'Bolonia 2280 LATU,' + '<br />\n' + 'Edificio Los Álamos, Of.103' + '<br />\n'+ 'Montevideo, CP 11500' + '<br />\n' + 'PH:+5982 2605 2332' + '<br />\n'
EMPRESA_HAWB_editar = 'OCEANLINK' + '\n' + 'Bolonia 2280 LATU,' + '\n' + 'Edificio Los Álamos, Of.103' + '\n'+ 'Montevideo, CP 11500' + '\n' + 'PH:+5982 2605 2332' + '\n'
EMPRESA_AWB = 'LOGISTICA TOTAL LTDA.' + '<br />\n' + 'Bolonia 2280 LATU,' + '<br />\n' + 'Edificio Los Álamos, Of.103' + '<br />\n'+ 'Montevideo,Uruguay. CP 11500' + '<br />\n' + 'PH:+5982 2605 2332' + '<br />\n'
EMPRESA_AWB_editar = 'LOGISTICA TOTAL LTDA.' + '\n' + 'Bolonia 2280 LATU,' + '\n' + 'Edificio Los Álamos, Of.103' + '\n'+ 'Montevideo,Uruguay. CP 11500' + '\n' + 'PH:+5982 2605 2332' + '\n'
EMPRESA_firma= 'OCEANLINK' + '<br />\n' + 'Bolonia 2280 LATU, Edificio Los Álamos, Of.103. Montevideo, CP 11500'
