# Generated by Django 4.2 on 2023-08-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('enviado_a', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=100)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ENVIADO', 'ENVIADO'), ('FALLIDO', 'FALLIDO')], max_length=10)),
                ('error', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Correos enviados',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
