# Generated by Django 4.2 on 2025-01-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_correoenviado_alter_account_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoenviado',
            name='emisor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='correoenviado',
            name='seguimiento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='correoenviado',
            name='enviado_a',
            field=models.CharField(max_length=500),
        ),
    ]
