# Generated by Django 4.2 on 2023-05-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
    ]
