# Generated by Django 4.2 on 2023-10-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_alter_clientes_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGrillaGuias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportista', models.IntegerField(blank=True, null=True)),
                ('empresa', models.CharField(blank=True, db_column='nom_empresa', max_length=250, null=True)),
                ('posicion', models.CharField(blank=True, db_column='posicion', max_length=250, null=True)),
                ('guia', models.CharField(blank=True, max_length=25, null=True)),
                ('prefijo', models.CharField(blank=True, max_length=10, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, db_column='estados', max_length=150, null=True)),
                ('refmaster', models.IntegerField(blank=True, db_column='referencia', null=True)),
                ('tipo', models.CharField(blank=True, db_column='tipodoc', max_length=1, null=True)),
                ('destino', models.CharField(blank=True, db_column='Destino', max_length=5, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('sucursal', models.SmallIntegerField(blank=True, db_column='Sucursal', null=True)),
            ],
            options={
                'db_table': 'VGrillaGuias',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='actividades',
            options={'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['empresa']},
        ),
        migrations.AlterModelOptions(
            name='depositos',
            options={'verbose_name_plural': 'Depositos'},
        ),
        migrations.AlterModelOptions(
            name='proyectos',
            options={'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='traficos',
            options={'verbose_name_plural': 'Traficos'},
        ),
        migrations.AlterModelOptions(
            name='vapores',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='vendedores',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='ciudades',
            name='paises_idinternacional',
            field=models.CharField(blank=True, db_column='Paises_IdInternacional', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='depositos',
            name='codigo',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='monedas',
            name='codigo',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='codigo',
            field=models.SmallIntegerField(db_column='Codigo', unique=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='codigo',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vapores',
            name='codigo',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='codigo',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
