# Generated by Django 4.2 on 2025-01-30 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0004_vsocioscomerciales_alter_ciudades_codigo_and_more'),
        ('seguimientos', '0002_vgrillaseguimientos_alter_seguimiento_armador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCargaaerea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('producto', models.IntegerField(blank=True, null=True)),
                ('bultos', models.IntegerField(blank=True, null=True)),
                ('bruto', models.FloatField(blank=True, null=True)),
                ('medidas', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('', '---------'), ('Bags', 'Bags'), ('Bales', 'Bales'), ('Big bags', 'Big bags'), ('Bing', 'Bing'), ('Boxes', 'Boxes'), ('Bulk', 'Bulk'), ('Bundles', 'Bundles'), ('Cartons', 'Cartons'), ('Cases', 'Cases'), ('Container', 'Container'), ('Crates', 'Crates'), ('Cylinder', 'Cylinder'), ('Declared', 'Declared'), ('Drums', 'Drums'), ('Envelope', 'Envelope'), ('Fireboard', 'Fireboard'), ('Flexitank', 'Flexitank'), ('Gallons', 'Gallons'), ('Jumbo', 'Jumbo'), ('Lot', 'Lot'), ('Packages', 'Packages'), ('Pallets', 'Pallets'), ('Pieces', 'Pieces'), ('Pipe', 'Pipe'), ('Platforms', 'Platforms'), ('Plywood case', 'Plywood case'), ('Reels', 'Reels'), ('Rolls', 'Rolls'), ('Sacks', 'Sacks'), ('Set', 'Set'), ('Skids', 'Skids'), ('Steel Pallets', 'Steel Pallets'), ('Tank', 'Tank'), ('Units', 'Units'), ('Wooden case', 'Wooden case'), ('Wooden rack', 'Wooden rack')], max_length=25, null=True)),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('mercaderia', models.TextField(blank=True, db_column='Mercaderia', null=True)),
                ('marcas', models.CharField(blank=True, db_column='Marcas', max_length=150, null=True)),
                ('nrocontenedor', models.CharField(blank=True, db_column='NroContenedor', max_length=15, null=True)),
                ('materialreceipt', models.CharField(blank=True, db_column='MaterialReceipt', max_length=30, null=True)),
                ('sobredimensionada', models.CharField(blank=True, db_column='Sobredimensionada', max_length=1, null=True)),
            ],
            options={
                'db_table': 'seguimientos_cargaaerea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VGrillaServiceaereo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('modo', models.CharField(blank=True, choices=[('P', 'Prepaid'), ('C', 'Collect')], max_length=1, null=True)),
                ('servicio', models.CharField(blank=True, max_length=500, null=True)),
                ('moneda', models.SmallIntegerField(blank=True, null=True)),
                ('tipogasto', models.CharField(blank=True, max_length=30, null=True)),
                ('arbitraje', models.FloatField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('detalle', models.CharField(blank=True, max_length=100, null=True)),
                ('secomparte', models.CharField(blank=True, max_length=1, null=True)),
                ('notomaprofit', models.BooleanField()),
                ('pinformar', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('notas', models.CharField(blank=True, db_column='Notas', max_length=100, null=True)),
                ('socio', models.IntegerField(blank=True, db_column='Socio', null=True)),
                ('id_servicio', models.SmallIntegerField()),
                ('id_moneda', models.SmallIntegerField()),
                ('id_socio', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'VGrillaServiceaereo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='attachhijo',
            name='idusuario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachhijo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='bl',
            name='loading',
            field=models.CharField(blank=True, db_column='Loading', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cargaaerea',
            name='producto',
            field=models.ForeignKey(db_column='producto', on_delete=django.db.models.deletion.PROTECT, related_name='prod_carga', to='mantenimientos.productos', to_field='codigo'),
        ),
        migrations.AlterField(
            model_name='cargaaerea',
            name='tipo',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Bags', 'Bags'), ('Bales', 'Bales'), ('Big bags', 'Big bags'), ('Bing', 'Bing'), ('Boxes', 'Boxes'), ('Bulk', 'Bulk'), ('Bundles', 'Bundles'), ('Cartons', 'Cartons'), ('Cases', 'Cases'), ('Container', 'Container'), ('Crates', 'Crates'), ('Cylinder', 'Cylinder'), ('Declared', 'Declared'), ('Drums', 'Drums'), ('Envelope', 'Envelope'), ('Fireboard', 'Fireboard'), ('Flexitank', 'Flexitank'), ('Gallons', 'Gallons'), ('Jumbo', 'Jumbo'), ('Lot', 'Lot'), ('Packages', 'Packages'), ('Pallets', 'Pallets'), ('Pieces', 'Pieces'), ('Pipe', 'Pipe'), ('Platforms', 'Platforms'), ('Plywood case', 'Plywood case'), ('Reels', 'Reels'), ('Rolls', 'Rolls'), ('Sacks', 'Sacks'), ('Set', 'Set'), ('Skids', 'Skids'), ('Steel Pallets', 'Steel Pallets'), ('Tank', 'Tank'), ('Units', 'Units'), ('Wooden case', 'Wooden case'), ('Wooden rack', 'Wooden rack')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='conexaerea',
            name='accion',
            field=models.CharField(blank=True, choices=[('DELIVERY', 'DELIVERY'), ('DISCHARGE', 'DISCHARGE'), ('RECEIPT', 'RECEIPT'), ('TRANSIT', 'TRANSIT')], db_column='Accion', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='conexaerea',
            name='cia',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='conexaerea',
            name='llegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conexaerea',
            name='modo',
            field=models.CharField(choices=[('MARITIMO', 'MARITIMO'), ('FLUVIAL', 'FLUVIAL'), ('TERRESTRE', 'TERRESTRE'), ('AEREO', 'AEREO')], max_length=15),
        ),
        migrations.AlterField(
            model_name='conexaerea',
            name='salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='activo',
            field=models.CharField(blank=True, db_column='Activo', default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='atmosferacontrolada',
            field=models.CharField(blank=True, db_column='AtmosferaControlada', default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='bonifcli',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='bultos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='envases',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='envases',
            name='consolidacion',
            field=models.SmallIntegerField(blank=True, db_column='Consolidacion', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='envase',
            field=models.CharField(choices=[('Bags', 'Bags'), ('Bales', 'Bales'), ('Big bags', 'Big bags'), ('Bing', 'Bing'), ('Boxes', 'Boxes'), ('Bulk', 'Bulk'), ('Bundles', 'Bundles'), ('Cartons', 'Cartons'), ('Cases', 'Cases'), ('Container', 'Container'), ('Crates', 'Crates'), ('Cylinder', 'Cylinder'), ('Declared', 'Declared'), ('Drums', 'Drums'), ('Envelope', 'Envelope'), ('Fireboard', 'Fireboard'), ('Flexitank', 'Flexitank'), ('Gallons', 'Gallons'), ('Jumbo', 'Jumbo'), ('Lot', 'Lot'), ('Packages', 'Packages'), ('Pallets', 'Pallets'), ('Pieces', 'Pieces'), ('Pipe', 'Pipe'), ('Platforms', 'Platforms'), ('Plywood case', 'Plywood case'), ('Reels', 'Reels'), ('Rolls', 'Rolls'), ('Sacks', 'Sacks'), ('Set', 'Set'), ('Skids', 'Skids'), ('Steel Pallets', 'Steel Pallets'), ('Tank', 'Tank'), ('Units', 'Units'), ('Wooden case', 'Wooden case'), ('Wooden rack', 'Wooden rack')], db_column='Envase', max_length=15),
        ),
        migrations.AlterField(
            model_name='envases',
            name='genset',
            field=models.CharField(blank=True, db_column='GenSet', default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='humedad',
            field=models.SmallIntegerField(blank=True, db_column='Humedad', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='marcas',
            field=models.CharField(blank=True, default='S/I', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='movimiento',
            field=models.CharField(choices=[('FCL/FCL', 'FCL/FCL'), ('FCL/LCL', 'FCL/LCL'), ('LCL/FCL', 'LCL/FCL'), ('LCL/LCL', 'LCL/LCL'), ('CY/CY', 'CY/CY'), ('CY/SD', 'CY/SD'), ('SD/SD', 'SD/SD'), ('SD/CY', 'SD/CY'), ('SD/CY', 'SD/CY'), ('Break Bulk', 'Break Bulk'), ('Ro/Ro', 'Ro/Ro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='envases',
            name='nrocontenedor',
            field=models.CharField(blank=True, default='S/I', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='precinto',
            field=models.CharField(blank=True, default='S/I', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='tara',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='temperatura',
            field=models.FloatField(blank=True, db_column='Temperatura', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='terminos',
            field=models.CharField(choices=[('FILO', 'FILO'), ('FIOS', 'FIOS'), ('FLT', 'FLT'), ('LIFO', 'LIFO'), ('LT', 'LT')], max_length=5),
        ),
        migrations.AlterField(
            model_name='envases',
            name='tipo',
            field=models.CharField(choices=[('Reefer', 'Reefer'), ('Hi Cube Reefer', 'Hi Cube Reefer'), ('Box', 'Box'), ('N.O.R.', 'N.O.R.'), ('Hi Cube', 'Hi Cube'), ('Dry', 'Dry'), ('Standard', 'Standard'), ('Part Container', 'Part Container'), ('CBM', 'CBM'), ('Open Top', 'Open Top')], max_length=20),
        ),
        migrations.AlterField(
            model_name='envases',
            name='unidad',
            field=models.CharField(choices=[('20', '20'), ('40', '40'), ('45', '45'), ('CBM', 'CBM'), ('CF', 'CF'), ('TON', 'TON'), ('M/T', 'M/T'), ('MIN', 'MIN'), ('FLAT', 'FLAT'), ('UNIT', 'UNIT'), ('LBS', 'LBS')], max_length=25),
        ),
        migrations.AlterField(
            model_name='envases',
            name='unidadtemp',
            field=models.CharField(blank=True, db_column='UnidadTemp', default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='envases',
            name='volumen',
            field=models.FloatField(blank=True, db_column='Volumen', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='awb',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='consignatario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='deposito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='embarcador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='estimadorecepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='modo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='moneda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='notificar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='operacion',
            field=models.CharField(blank=True, choices=[('', ''), ('IMPORTACION', 'IMPORTACION'), ('EXPORTACION', 'EXPORTACION'), ('IMPORTACION LCL', 'IMPORTACION LCL'), ('IMPORTACION FCL', 'IMPORTACION FCL'), ('IMPORTACION PART CONT.', 'IMPORTACION PART CONT.'), ('TRANSITO FCL', 'TRANSITO FCL'), ('IMPORTACION CONSOLIDADA', 'IMPORTACION CONSOLIDADA'), ('REEMBARCO', 'REEMBARCO'), ('TRANSITO', 'TRANSITO'), ('TRASLADO', 'TRASLADO'), ('MUESTRA', 'MUESTRA')], db_column='Operacion', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='originales',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], db_column='Originales', default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='pago',
            field=models.CharField(blank=True, choices=[('Collect', 'Collect'), ('Prepaid', 'Prepaid')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='status',
            field=models.CharField(blank=True, choices=[('ARRIBADO', 'ARRIBADO'), ('CONFIRMADO', 'CONFIRMADO'), ('CANCELADO', 'CANCELADO'), ('RESERVADO', 'RESERVADO'), ('UNIFICADO', 'UNIFICADO'), ('CERRADO', 'CERRADO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='transportista',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='vaporcli',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='vendedor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceaereo',
            name='modo',
            field=models.CharField(blank=True, choices=[('P', 'Prepaid'), ('C', 'Collect')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='serviceaereo',
            name='moneda',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='serviceaereo',
            name='secomparte',
            field=models.CharField(blank=True, choices=[('S', 'SI'), ('N', 'NO')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='serviceaereo',
            name='servicio',
            field=models.SmallIntegerField(),
        ),
    ]
